name: Publish To GH Pages

on:
  workflow_dispatch: {}
  push:
    branches: 
      - main
jobs:
  publish-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Initialize Python venv
        run: make init
        # env:
        #   MKDOCS_MATERIAL_INSIDER_TOKEN: ${{ secrets.MKDOCS_MATERIAL_INSIDER_TOKEN }}
      - name: Publish to GH Pages
        run: make mkdocs-publish
